namespace _01_Framework.Infrastructure
{
    public class Times
    {
       public static List<TimeViewModel> List = new List<TimeViewModel>
        {
            new TimeViewModel { Value = "07:30" },
            new TimeViewModel { Value = "07:40" },
            new TimeViewModel { Value = "07:50" },
            new TimeViewModel { Value = "08:00" },
            new TimeViewModel { Value = "08:10" },
            new TimeViewModel { Value = "08:20" },
            new TimeViewModel { Value = "08:30" },
            new TimeViewModel { Value = "08:40" },
            new TimeViewModel { Value = "08:50" },
            new TimeViewModel { Value = "09:00" },
            new TimeViewModel { Value = "09:10" },
            new TimeViewModel { Value = "09:20" },
            new TimeViewModel { Value = "09:30" },
            new TimeViewModel { Value = "09:40" },
            new TimeViewModel { Value = "09:50" },
            new TimeViewModel { Value = "10:00" },
            new TimeViewModel { Value = "10:10" },
            new TimeViewModel { Value = "10:20" },
            new TimeViewModel { Value = "10:30" },
            new TimeViewModel { Value = "10:40" },
            new TimeViewModel { Value = "10:50" },
            new TimeViewModel { Value = "11:00" },
            new TimeViewModel { Value = "11:10" },
            new TimeViewModel { Value = "11:20" },
            new TimeViewModel { Value = "11:30" },
            new TimeViewModel { Value = "11:40" },
            new TimeViewModel { Value = "11:50" },
            new TimeViewModel { Value = "12:00" },
            new TimeViewModel { Value = "12:10" },
            new TimeViewModel { Value = "12:20" },
            new TimeViewModel { Value = "12:30" },
            new TimeViewModel { Value = "12:40" },
            new TimeViewModel { Value = "12:50" },
            new TimeViewModel { Value = "13:00" },
            new TimeViewModel { Value = "13:10" },
            new TimeViewModel { Value = "13:20" },
            new TimeViewModel { Value = "13:30" },
            new TimeViewModel { Value = "13:40" },
            new TimeViewModel { Value = "13:50" },
            new TimeViewModel { Value = "14:00" },
            new TimeViewModel { Value = "14:10" },
            new TimeViewModel { Value = "14:20" },
            new TimeViewModel { Value = "14:30" },
            new TimeViewModel { Value = "14:40" },
            new TimeViewModel { Value = "14:50" },
            new TimeViewModel { Value = "15:00" },
            new TimeViewModel { Value = "15:10" },
            new TimeViewModel { Value = "15:20" },
            new TimeViewModel { Value = "15:30" },
            new TimeViewModel { Value = "15:40" },
            new TimeViewModel { Value = "15:50" },
            new TimeViewModel { Value = "16:00" },
            new TimeViewModel { Value = "16:10" },
            new TimeViewModel { Value = "16:20" },
            new TimeViewModel { Value = "16:30" },
            new TimeViewModel { Value = "16:40" },
            new TimeViewModel { Value = "16:50" },
            new TimeViewModel { Value = "17:00" },
            new TimeViewModel { Value = "17:10" },
            new TimeViewModel { Value = "17:20" },
            new TimeViewModel { Value = "17:30" },
            new TimeViewModel { Value = "17:40" },
            new TimeViewModel { Value = "17:50" },
            new TimeViewModel { Value = "18:00" },
            new TimeViewModel { Value = "18:10" },
            new TimeViewModel { Value = "18:20" },
            new TimeViewModel { Value = "18:30" },
            new TimeViewModel { Value = "18:40" },
            new TimeViewModel { Value = "18:50" },
            new TimeViewModel { Value = "19:00" },
            new TimeViewModel { Value = "19:10" },
            new TimeViewModel { Value = "19:20" },
            new TimeViewModel { Value = "19:30" },
            new TimeViewModel { Value = "19:40" },
            new TimeViewModel { Value = "19:50" },
            new TimeViewModel { Value = "20:00" },
            new TimeViewModel { Value = "20:10" },
            new TimeViewModel { Value = "20:20" },
            new TimeViewModel { Value = "20:30" }
        };
    }
}
