namespace _01_Framework.Infrastructure
{
    public class Times
    {
       public static List<TimeViewModel> List = new List<TimeViewModel>
        {
            new TimeViewModel { Value = "08:00" },
            new TimeViewModel { Value = "08:15" },
            new TimeViewModel { Value = "08:30" },
            new TimeViewModel { Value = "08:45" },
            new TimeViewModel { Value = "09:00" },
            new TimeViewModel { Value = "09:15" },
            new TimeViewModel { Value = "09:30" },
            new TimeViewModel { Value = "09:45" },
            new TimeViewModel { Value = "10:00" },
            new TimeViewModel { Value = "10:15" },
            new TimeViewModel { Value = "10:30" },
            new TimeViewModel { Value = "10:45" },
            new TimeViewModel { Value = "11:00" },
            new TimeViewModel { Value = "11:15" },
            new TimeViewModel { Value = "11:30" },
            new TimeViewModel { Value = "11:45" },
            new TimeViewModel { Value = "12:00" },
            new TimeViewModel { Value = "12:15" },
            new TimeViewModel { Value = "12:30" },
            new TimeViewModel { Value = "12:45" },
            new TimeViewModel { Value = "13:00" },
            new TimeViewModel { Value = "13:15" },
            new TimeViewModel { Value = "13:30" },
            new TimeViewModel { Value = "13:45" },
            new TimeViewModel { Value = "14:00" },
            new TimeViewModel { Value = "14:15" },
            new TimeViewModel { Value = "14:30" },
            new TimeViewModel { Value = "14:45" },
            new TimeViewModel { Value = "15:00" },
            new TimeViewModel { Value = "15:15" },
            new TimeViewModel { Value = "15:30" },
            new TimeViewModel { Value = "15:45" },
            new TimeViewModel { Value = "16:00" },
            new TimeViewModel { Value = "16:15" },
            new TimeViewModel { Value = "16:30" },
            new TimeViewModel { Value = "16:45" },
            new TimeViewModel { Value = "17:00" },
            new TimeViewModel { Value = "17:15" },
            new TimeViewModel { Value = "17:30" },
            new TimeViewModel { Value = "17:45" },
            new TimeViewModel { Value = "18:00" },
            new TimeViewModel { Value = "18:15" },
            new TimeViewModel { Value = "18:30" },
            new TimeViewModel { Value = "18:45" },
            new TimeViewModel { Value = "19:00" },
            new TimeViewModel { Value = "19:15" },
            new TimeViewModel { Value = "19:30" },
            new TimeViewModel { Value = "19:45" },
            new TimeViewModel { Value = "20:00" },
            new TimeViewModel { Value = "20:15" },
            new TimeViewModel { Value = "20:30" },
            new TimeViewModel { Value = "20:45" }
        };
    }
}
