namespace _01_Framework.Infrastructure
{
    public class Universities
    {
       public static List<UniversityViewModel> List = new List<UniversityViewModel>
        {
            new UniversityViewModel("آموزشکده سما ابهر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما اراک", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما اردبیل", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ارسنجان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ارومیه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ازگل", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما اسلام آباد غرب", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما اسلامشهر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما امیدیه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما اندیشه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما اهواز", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ایذه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ایلام", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما آباده", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما آزادشهر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما آستارا", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما آیت اله آملی", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بابل", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بجنورد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بروجرد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بناب", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بندر انزلی", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بندر عباس", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بهبهان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بوشهر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما بیرجند", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما پارس آباد مغان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما پاکدشت", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تاکستان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تالش", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تبریز", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تربت جام", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تربت حیدریه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تنکابن", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تهران", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تهران-کن", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما تهرانسر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما جهرم", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما جیرفت", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما چالوس", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما خرم آباد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما خلخال", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما خمین", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما خمینی شهر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما خوراسگان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما خوی", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما داراب", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما دزفول", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما دماوند", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما رشت", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما رودبار", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما رودهن", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما زاهدان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما زنجان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ساری", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ساوه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما سبزوار", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما سراب", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما سنندج", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما سهند", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما سوسنگرد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما سیاهکل", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما شاهرود", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما شبستر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما شریعتی", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما شهرکرد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما شوشتر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما شیراز", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما شیروان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما علی آبادکتول", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما فیروز آباد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما قائمشهر-کیاکلا", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما قائنات", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما قشم", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما قم", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما قوچان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما کازرون", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما کاشمر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما کرج", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما کرمان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما کرمانشاه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما گچساران", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما گرگان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما گرمسار", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما گناباد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما لار-لارستان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما لاهیجان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما لنگرود", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ماهشهر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما مراغه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما مرند", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما مرودشت", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما مسجد سلیمان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما مشهد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ملایر", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ممقان", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما مهاباد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما میاندوآب", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما میانه", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما نجف آباد", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما نیشابور", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما ورامین", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما یاسوج", UniversityTypesConstants.Sama),
            new UniversityViewModel("آموزشکده سما یزد", UniversityTypesConstants.Sama),
            new UniversityViewModel("دانشگاه آزاد اسلامی ابرکوه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ابهر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اراک", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اردستان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اردکان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ارسنجان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ارومیه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی استهبان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اسلامشهر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اشکذر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اصفهان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اقلید", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی امارات متحده عربی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اندیمشک", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی اهر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ایذه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ایلام", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی آباد مغان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی آباده", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی آیت الله آملی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بابل", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بافت", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بجنورد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بردسیر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بناب", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بندر لنگه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بندرعباس", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بهبهان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بوشهر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بوکان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی بیرجند", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تاکستان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تبریز", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تربت جام", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تفت", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تفرش", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تهران پزشکی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تهران جنوب", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تهران شرق", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تهران شمال", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی تهران مرکزی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی جهرم", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی جیرفت", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی خدابنده", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی خمین", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی خوراسگان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی خوی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی دامغان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی دزفول", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی دندانپزشکی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی دولت آباد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی رشت", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی رفسنجان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی زابل", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی زاهدان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی زنجان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ساری", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ساوه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی سبزوار", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی سروستان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی سقز", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی سمنان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی سنندج", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی سواد کوه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شاهرود", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شبستر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شهر قدس", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شهر مجلسی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شهرضا", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شهرکرد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شوشتر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شیراز", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی شیروان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی طبس", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی علوم دارویی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی علوم و تحقیقات ", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی علی ابادکتول", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی فراهان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی فردوس", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی فلاورجان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی فیروزآباد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی فیروزکوه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی قزوین", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی قوچان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی کرج", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی کرمان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی کرمانشاه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی گچساران", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی گرگان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی گرمسار", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی لارستان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی لامرد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی لاهیجان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ماهشهر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی مبارکه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی مراغه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی مرند", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی مرودشت", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی مسجد سلیمان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی مشهد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ملایر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی مهاباد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی میاندواب", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی میانه", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی نایین", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی نجف آباد", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی نطنز", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی نکا", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی نی ریز", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی نیشابور", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی همدان", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی واحد مجازی", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی ورامین پیشوا", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی یادگار امام", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی یاسوج", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه آزاد اسلامی آبادان و خرمشهر", UniversityTypesConstants.Azad),
            new UniversityViewModel("دانشگاه بین‌المللی پیام نور عسلویه", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور (سازمان مرکزی)", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور اِوَز", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور ابهر", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور اردبیل", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور اردکان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور اسفراین", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور اقلید", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور الوند", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور اهرم", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور ایلام", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور آمل", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور بانه", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور برازجان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور بردسکن", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور بوانات", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور بوشهر", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور بیرجند", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور تبریز", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور تربت حیدریه", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور تهران غرب", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور جم", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور جهرم", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور جیرفت", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور خرمدره", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور خوانسار", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور خورموج", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور دزفول", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور دهدشت", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور دهلران", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور دیر", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور رامیان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور رودهن", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور رینه", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور زنجان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور ساری", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور ساوه", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور سروستان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور سلطانیه-زنجان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور سمیرم", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور شبانکاره", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور شبستر", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور شهریار", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور شوش", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور شیراز", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور طارم زنجان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور طالقان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور فیروزآباد", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور قزوین", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور قم", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور کازرون", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور کامیاران", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور کرج", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور کنگان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور گرگان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور گرمسار", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور گلپایگان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور گناباد", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور گناوه", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور گنبد", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور لالجین", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور مشهد", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور ممقان", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور نجف‌آباد", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور نیشابور", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور هشترود", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه پیام نور واحد مهدی‌شهر", UniversityTypesConstants.PayamNoor),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی اردبیل", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی اصفهان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی البرز", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی ایلام", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی آذربایجان شرقی", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی آذربایجان غربی", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی بوشهر", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی تهران", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی چهارمحال بختیاری", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی خراسان جنوبی", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی خراسان رضوی", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی خراسان شمالی", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی خوزستان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی زنجان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی سمنان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی سیستان و بلوچستان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی فارس", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی قزوین", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی قم", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی کردستان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی کرمان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی کرمانشاه", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی کهگیلویه و بویراحمد", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی گلستان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی گیلان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی لرستان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی مازندران", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی مرکزی", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی هرمزگان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی همدان", UniversityTypesConstants.ElmiKarbordi),
            new UniversityViewModel("دانشگاه جامع علمی کاربردی یزد", UniversityTypesConstants.ElmiKarbordi),
             new UniversityViewModel("آموزشکده آمار و انفورماتیک", UniversityTypesConstants.Dolati),
            new UniversityViewModel("آموزشکده فنی پسران اراک", UniversityTypesConstants.Dolati),
            new UniversityViewModel("آموزشکده فنی پسران دزفول (دکتر عصاریان)", UniversityTypesConstants.Dolati),
            new UniversityViewModel("آموزشکده فنی پسران علی آبادکتول", UniversityTypesConstants.Dolati),
            new UniversityViewModel("آموزشکده فنی پسران گلپایگان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("آموزشکده فنی علی ابن ابیطالب بم", UniversityTypesConstants.Dolati),
            new UniversityViewModel("آموزشکده فنی مهندسی ایلام", UniversityTypesConstants.Dolati),
            new UniversityViewModel("آموزشکده محیط زیست کرج", UniversityTypesConstants.Dolati),
            new UniversityViewModel("پژوهشکده محیط زیست و توسعه پایدار", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده پست و مخابرات ایران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده تربیت دبیر فنی صومعه سرا", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده حفاظت و بهداشت کار", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده صدا و سیما", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده صنایع مخابرات ایران (شیراز)", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده علمی کاربردی پست و مخابرات", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده علوم سیاسی، فرهنگ و ارتباطات شهید محلاتی (ره)", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده علوم قضایی و خدمات اداری", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی امام خمینی (ره) سبزوار", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی انقلاب اسلامی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی پسران نیشابور", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی دکتر شریعتی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی شهید شمسی پور", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی شهید مهاجر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی ملاصدرا رامسر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی مهندسی ثامن الحجج (ع) مشهد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی مهندسی شهید محمد منتظری مشهد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی مهندسی علی‌آباد کتول", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده فنی ولیعصر (عج) تهران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده کشاورزی شهید رجایی نیشابور", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده کشاورزی و دامپروری تربت جام", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده و آموزشکده دختران آمل", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه اراک", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه اردکان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه ارومیه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه اصفهان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه افسری امام علی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه الزهرا", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه امام باقر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه امام صادق", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه ایلام", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه آیت‌الله‌العظمی بروجردی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه بجنورد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه بزرگمهر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه بناب", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه بوعلی سینا همدان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه بیرجند", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه بین‌المللی امام خمینی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تبریز", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تحصیلات تکمیلی صنعتی کرمان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تحصیلات تکمیلی علوم پایه زنجان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تخصصی فناوری‌های نوین آمل", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تربت حیدریه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تربیت دبیر شهید رجایی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تربیت مدرس", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تفرش", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه تهران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه جامع امام حسین", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه جهرم", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه جیرفت", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه حضرت معصومه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه حضرت نرجس رفسنجان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه حکیم سبزواری", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه خلیج فارس بوشهر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه خوارزمی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه دامغان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه دریانوردی و علوم دریایی چابهار", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه رازی کرمانشاه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه زابل", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه زنجان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه سلمان فارسی کازرون", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه سمنان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه سید جمال‌الدین اسدآبادی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه سیستان و بلوچستان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شاهد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شهرکرد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شهید باهنر کرمان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شهید بهشتی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شهید چمران اهواز", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شهید مدنی آذربایجان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شهید مطهری", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه شیراز", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنایع و معادن ایران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعت نفت", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی اراک", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی اردبیل", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی ارومیه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی اصفهان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی امیرکبیر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی بیرجند", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی جندی‌شاپور", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی خاتم‌الانبیا", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی خواجه نصیرالدین طوسی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی سهند", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی سیرجان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی سیستان و بلوچستان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی شاهرود", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی شریف", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی شهدای هویزه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی شیراز", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی قم", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی قوچان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی کرمانشاه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی مالک اشتر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی نوشیروانی بابل", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه صنعتی همدان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علامه طباطبایی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علم و صنعت ایران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علم و فناوری مازندران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علوم انتظامی امین", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علوم کشاورزی و منابع طبیعی ساری", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علوم کشاورزی و منابع طبیعی ساری", UniversityTypesConstants.Dolati), // دو بار اضافه شده
            new UniversityViewModel("دانشگاه علوم کشاورزی و منابع طبیعی گرگان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علوم و فنون دریایی خرمشهر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علوم و معارف قرآن کریم دانشگاه علوم قرآنی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه علوم وفنون فارابی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه فردوسی مشهد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه فرزانگان سمنان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه فسا", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه قم", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه کاشان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه کردستان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه کشاورزی و منابع طبیعی رامین", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه کوثر بجنورد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه گرمسار", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه گلستان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه گنبد کاووس", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه گیلان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه لرستان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه مازندران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه محقق اردبیلی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه مذاهب اسلامی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه مراغه", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه ملایر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه مهندسی علوم و فناوری‌های نوین گلبهار", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه میبد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه نیشابور", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه هرمزگان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه هنر اسلامی تبریز", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه هنر اصفهان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه هنر تهران", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه هنر شیراز", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه هوایی شهید ستاری", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه ولایت ایرانشهر", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه ولی‌عصر رفسنجان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه یاسوج", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشگاه یزد", UniversityTypesConstants.Dolati),
            new UniversityViewModel("مرکز آموزش عالی تربیت مربی عقیدتی سیاسی", UniversityTypesConstants.Dolati),
            new UniversityViewModel("مرکز آموزش عالی فنی الغدیر زنجان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("مرکز بین‌المللی علوم و تکنولوژی پیشرفته و علوم محیطی کرمان", UniversityTypesConstants.Dolati),
            new UniversityViewModel("دانشکده علوم پزشکی اسدآباد", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی اسفراین", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی آبادان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی بهبهان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی تربت جام", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی خلخال", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی خمین", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی خوی", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی ساوه", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی سراب", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی سیرجان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی شوشتر", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی گراش", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی لارستان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی مراغه", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده علوم پزشکی نیشابور", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم بهزیستی و توانبخشی", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی اراک", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی ارتش", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی اردبیل", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی ارومیه", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی اصفهان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی البرز", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی ایران", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی ایرانشهر", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی ایلام", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی بابل", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی بقیةالله", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی بم", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی بوشهر", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی بیرجند", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی تبریز", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی تربت حیدریه", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی تهران", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی جندی‌شاپور", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی جهرم", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی جیرفت", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی خراسان شمالی", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی دزفول", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی رفسنجان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی زابل", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی زاهدان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی زنجان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی سبزوار", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی سمنان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی شاهد", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی شاهرود", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی شهرکرد", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی شهید بهشتی", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی شهید صدوقی", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی شیراز", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی فسا", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی قزوین", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی قم", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی کاشان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی کردستان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی کرمان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی کرمانشاه", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی گلستان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی گناباد", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی گیلان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی لرستان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی مازندران", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی مشهد", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی هرمزگان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی همدان", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشگاه علوم پزشکی یاسوج", UniversityTypesConstants.PezeshkiDolati),
            new UniversityViewModel("دانشکده اصول الدین", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده آمار و انفورماتیک سازمان سنجش", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده ریاضی و کامپیوتر خوانسار", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده علوم حدیث", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده فنی و مهندسی گلپایگان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده کشاورزی شیروان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده کشاورزی و دامپروری تربت جام", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده کشاورزی و منابع طبیعی داراب", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشکده معارف قرآنی اصفهان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه ابرار", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه ادیان و مذاهب", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه آل طه", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه باقرالعلوم", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه بین‌المللی امام رضا", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه رایانه‌ای تهران", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه سوره", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه شمال (آمل)", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه شیخ بهایی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه صنعتی سجاد مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه علامه محدث نوری", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه علم و فرهنگ", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه علوم اسلامی رضوی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه علوم و فنون مازندران", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه غیرانتفاعی اندیشه", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه غیرانتفاعی صدرالمتالهین (صدرا)", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه غیرانتفاعی هیمن", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("دانشگاه مفید", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مجتمع آموزش عالی اسفراین", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مجتمع آموزش عالی بم", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مجتمع آموزش عالی سراوان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مجتمع آموزش عالی گناباد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مجتمع آموزش عالی لارستان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مرکز آموزش عالی استهبان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مرکز آموزش عالی اقلید", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مرکز آموزش عالی شرکت داده پردازی ایران", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مرکز آموزش عالی کاشمر", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مرکز آموزش عالی لامرد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مرکز آموزش عالی محلات", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مرکز آموزش عالی ممسنی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("موسسه آموزش عالی ارشاد دماوند", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("موسسه آموزش عالی سراج", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("موسسه آموزش عالی علاءالدوله سمنانی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("موسسه آموزش عالی کاوش", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("موسسه آموزش عالی مهرالبرز", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسهٔ آموزش عالی جهاد دانشگاهی خوزستان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی ادیب مازندران", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی ادیبان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی ادیبان یزد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی اسرار مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی اقبال لاهوری مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی ایوانکی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی آباد (آبیک)", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی آرادان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی آمل", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی باختر ایلام", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی بعثت کرمان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی بهار مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی پارس رضوی گناباد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی پارسا بابلسر", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی پارسیان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی پویا (یاسوج)", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی پویندگان دانش چالوس", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی پیام گلپایگان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی تابران (مشهد)", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی توسعه دانش سنندج", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی ثامن نیشابور", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی جابر بن حیان-رشت", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی جامی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی جاوید جیرفت", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی جهاد دانشگاهی استان یزد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی حکمت قم", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی خاتم", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی خاوران مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی خراسان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی خرد گرایان مطهر مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی خیام مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی دارالعلم یزد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی دانش پژوهان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی دانشوران تبریز", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی دیلمان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی راه دانش بابل", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی راهبرد شمال رشت", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی رجا قزوین", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی رسام", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی رشدیه -تبریز", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی روزبه زنجان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی روزبهان ساری", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی ساریان ساری", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سبحان نیشابور", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سبز آمل", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سبلان اردبیل", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سپاهان اصفهان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سپهر اصفهان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سفیر دانش ایلام", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سلمان(مشهد)", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی سینا کاشان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی شاهرود", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی شرق گلستان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی شمس گنبدکاووس", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی شهاب دانش قم", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی شهریار آستارا", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی شهید اشرفی اصفهانی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی صالحان قایم شهر", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی صفاهان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی صنعتی فولاد اصفهان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی صنعتی مازندران", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی طبرستان چالوس", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی طبری بابل", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی طلوع مهر قم", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی عبدالرحمان صوفی رازی زنجان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی عطار مشهد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی علامه جعفری رفسنجان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی علامه دهخدا قزوین", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی علامه فیض کاشانی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی علوم و توسعه آریا", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی علوم و فناوری آریان بابل", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی علوم و فناوری سپاهان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی غزالی - قزوین", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی غیاث الدین جمشید کاشانی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی غیرانتفاعی تعالی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی غیرانتفاعی کارون", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی غیرانتفاعی گنجنامه همدان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی فردوس", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی فنی کرمان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی کار", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی کسری رامسر", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی کنسرواتور تهران", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی کومش سمنان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی لامعی گرگانی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی مازیار رویان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی مهد علم کاشان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی مهر اراک", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی مهر آستان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی مهرگان محلات", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی میرداماد گرگان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی میرعماد قزوین", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی میزان تبریز", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی ناصر خسرو", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی نبی اکرم تبریز", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی نجف آباد", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی نهاوند", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی نورطوبی", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی هدف", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی هرمزان", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش عالی هنر کمال الملک نوشهر", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزش مولانا", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("مؤسسه آموزشی و پژوهشی امام خمینی(ره)", UniversityTypesConstants.GheireEntefaei),
            new UniversityViewModel("پردیس امام خمینی گرگان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس الزهرا زنجان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس الزهرا سمنان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس امام جعفر صادق ایلام", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس امام جعفر صادق بجنورد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس امام سجاد بیرجند", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس امام علی رشت", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس امام محمد باقر بجنورد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس امیر کبیر کرج", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس آیت‌الله خامنه‌ای گرگان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس آیت‌الله طالقانی قم", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس آیت‌الله کمالوند خرم‌آباد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس بحرالعلوم شهرکرد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس بنت‌الهدی صدر اردبیل", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس بنت‌الهدی صدر بوشهر", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس بنت‌الهدی صدر رشت", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس بنت‌الهدی صدر سنندج", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس بنت‌الهدی صدر قزوین", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس حضرت رسول اکرم اهواز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس حضرت معصومه قم", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس حکیم ابوالقاسم فردوسی کرج", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس خواجه نصیرالدین طوسی کرمان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس دکتر شریعتی ساری", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس رسالت زاهدان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس زینب کبری اراک", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس زینبیه پیشوا", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید ایزدپناه یاسوج", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید باهنر اراک", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید باهنر اصفهان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید باهنر بیرجند", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید باهنر شهرکرد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید باهنر شیراز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید باهنر کرمان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید باهنر همدان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید بهشتی بندرعباس", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید بهشتی زنجان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید پاک‌نژاد یزد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید چمران تهران", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید دکتر بهشتی مشهد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید رجایی ارومیه", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید رجایی سمنان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید رجایی شیراز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید رجایی قزوین", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید رجایی کرمانشاه", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید صدوقی کرمانشاه", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید مدرس ایلام", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید مدرس سنندج", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید مطهری زاهدان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید مفتح شهر ری", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید مقصودی همدان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس شهید هاشمی نژاد مشهد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس صدیقه طاهره ساری", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس علامه امینی تبریز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس علامه طباطبایی اردبیل", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس علامه طباطبایی ارومیه", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس علامه طباطبایی بوشهر", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس علامه طباطبایی خرم‌آباد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس فاطمه الزهرا (س) تبریز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس فاطمه الزهرا اهواز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس فاطمه الزهرا بندرعباس", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس فاطمه الزهرا یزد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس فاطمه الزهرا(س) اصفهان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس کوثر یاسوج", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس نسیبه تهران", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("پردیس‌ها", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی ابن سینا همدان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی امام جعفر صادق بهبهان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی امام خمینی سلماس", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی امام خمینی کاشان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی امام رضا اندیمشک", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی آزادگان نیر", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی بعثت شیراز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی بلال حبشی تهران", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی بنت‌الهدی صدر فردوس", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی بیت‌الهدی آمل", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی ثامن‌الحجج مشهد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی حضرت خدیجه کبری دزفول", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی حضرت فاطمه قائم‌شهر", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی دانشور نیشابور", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی دکتر آیت نجف‌آباد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی زینب کبری بروجرد", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی زینب کبری کازرون", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی سلمان فارسی شیراز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهدای مکه تهران", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید باهنر تهران", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید بهشتی اقلید", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید بهشتی تهران", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید بهشتی گنبدکاووس", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید حسینی طباطبایی زاهدان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید رجایی اصفهان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید رجایی بابل", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید رجائی تربت حیدریه", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید شرافت تهران", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید مدنی قم", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید مطهری خوی", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید مطهری زرقان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید مطهری نوشهر", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شهید میرشاکی الیگودرز", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی شیخ مرتضی انصاری دزفول", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی عترت واوان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی علامه طباطبایی سبزوار", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("مرکز آموزش عالی لارستان", UniversityTypesConstants.Farhangian),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ابرکوه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای اراک", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای اردبیل", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای اردکان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ارزوئیه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ارومیه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای استهبان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای اسلام آباد غرب", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای اصفهان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای اقلید", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای امیریه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای اهواز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ایلام", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای آباده", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای آستانه اشرفیه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای آمل", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بابل", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بافت", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بجنورد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بروجرد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بروجن", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بم", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بندر انزلی", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بندرعباس", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بهشهر", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بوشهر", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای بیرجند", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای تبریز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای تربت حیدریه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای تفت", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای جاجرم", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای جونقان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای جیرفت", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای خاتم", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای خرم‌آباد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای خلخال", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای خمین", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای خوانسار", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای خوی", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای داراب", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای دزفول", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای دورود", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای رامسر", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای رستم‌آباد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای رشت", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای رفسنجان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای زابل", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای زاهدان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای زرند", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای زنجان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ساری", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ساوه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای سبزوار", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای سراب", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای سقز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای سمنان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای سنندج", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای سیرجان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شاهرود", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شاهین‌شهر", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره دو اهواز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره دو تبریز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره دو زاهدان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره دو ساری", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره دو شیراز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره دو کرمان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره دو کرمانشاه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره یک زاهدان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شماره یک کرمانشاه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شهر بابک", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شهرضا", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شهرکرد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شیراز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای شیروان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای صفادشت", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای طبس", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای علی‌آباد کتول", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای فردوس", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای فیروزآباد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای قائن", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای قزوین", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای قم", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای قوچان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای کازرون", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای کاشان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای کرج", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای کرمان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای کرمانشاه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای گرگان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای گناباد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای گنبد کاووس", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای لارستان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای مراغه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای مرودشت", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای مشهد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ملایر", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ممسنی", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای میانه", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای میبد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای میناب", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای نهاوند", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای نوشهر", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای نی‌ریز", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای نیشابور", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای همدان", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای یاسوج", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای یزد", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای امام خمینی", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای امام علی", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای امیرکبیر", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای ثامن‌الحجج", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای خوارزمی", UniversityTypesConstants.FaniHerfeEi),
            new UniversityViewModel("آموزشکده فنی و حرفه‌ای دیباج", UniversityTypesConstants.FaniHerfeEi)

        };

        public static string GetName(int id)
        {
            var name = "";
            foreach (var i in List)
            {
                if (i.Id == id)
                {
                    name= i.Name;
                }
            }

            return name;
        }

        public static List<string> GetUniversitiesByType(int typeId)
        {
            var result = new List<string>();

            foreach (var i in List)
            {
                if (i.UniversityTypeId == typeId)
                {
                    result.Add(i.Name);
                }
            }

            return result;

            
        }
    }
}
